### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by burf2000** [IBM-Bluemix/IBM-Watson-Speech-QA-iOS#1]
Is there anyway you can update this for the current setup, I think terminology has changed especially around MOBILE CLIENT ACCESS, it now gives you Google, Facebook and custom setup.  I have not found where to enter the bundle ID in to Bluemix

Also the iOS no longer compiles due to TDReachability.h

**Comment by triceam** [comment]
I just committed my latest project.  It should compile, and now uses the Watson Speech SDK for iOS for streaming audio transcription (faster/lower latency and provides realtime iterations of transcripted text).   You should be able to just download the latest and follow the instructions in the readme file to get everything working.  Let me know if you have any issues - i may have accidentally missed a step when updating the readme.   It should also compile now when using the latest CocoaPods configuration.
