### ISSUE TITLE
WebSocketUploader - data written but we're not connected yet

### ISSUE THREAD

**Issue by Naim08** [IBM-Bluemix/IBM-Watson-Speech-QA-iOS#2]
I keep getting this error as I ran the application "WebSocketUploader - data written but we're not connected yet".

**Comment by triceam** [comment]
Did you setup authentication for your Watson speech to text service using the credentials available in your Bluemix dashboard (specifically, the credentials for your STT service instance, not your bluemix auth credentials)?  You will see this message if you have not properly authenticated the STT service.

**Comment by Naim08** [comment]
Thank You, I figured that was the issue.
